// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRC7rSpbRhgcsWRA0bMqopGkXwNnr7bA',
    appId: '1:894741759281:web:f3bef942c7efe572081c10',
    messagingSenderId: '894741759281',
    projectId: 'loanapp-7d621',
    authDomain: 'loanapp-7d621.firebaseapp.com',
    storageBucket: 'loanapp-7d621.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQmBh_Pw927efKCS6XTSlqdy8_wrLx-Y',
    appId: '1:894741759281:android:ab0683c0b78c5d02081c10',
    messagingSenderId: '894741759281',
    projectId: 'loanapp-7d621',
    storageBucket: 'loanapp-7d621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuads6WEiawT5WkR--NmeRIQIkMouKyYg',
    appId: '1:894741759281:ios:c9d945b16cebb2a4081c10',
    messagingSenderId: '894741759281',
    projectId: 'loanapp-7d621',
    storageBucket: 'loanapp-7d621.appspot.com',
    iosBundleId: 'com.example.loanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuads6WEiawT5WkR--NmeRIQIkMouKyYg',
    appId: '1:894741759281:ios:6d4d59ff2c681e84081c10',
    messagingSenderId: '894741759281',
    projectId: 'loanapp-7d621',
    storageBucket: 'loanapp-7d621.appspot.com',
    iosBundleId: 'com.example.loanapp.RunnerTests',
  );
}
